import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#012E40',
  },
  kav: {
    flex: 1,
  },
  pageContent: {
    flexGrow: 1,
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 24,
    backgroundColor: '#012E40',
  },
  container: {
    width: '100%',
    alignItems: 'center',
  },
  title: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#fafafa',
    textAlign: 'center',
    marginBottom: 16,
  },
  input: {
    width: '80%',
    height: 50,
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingHorizontal: 12,
    fontSize: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#025159',
  },
  button: {
    backgroundColor: '#038C8C',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: 'center',
    width: '80%',
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  scrollArea: {
    width: '90%',
    backgroundColor: '#ffffffee',
    borderRadius: 12,
    padding: 20,
    marginTop: 12,
    borderLeftWidth: 5,
    borderLeftColor: '#F28705',
    minHeight: 0,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginBottom: 12,
  },
  itemInput: {
    flex: 1,
    height: 50,
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingHorizontal: 12,
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#025159',
  },
  addButton: {
    height: 50,
    width: 50,
    backgroundColor: '#F28705',
    marginLeft: 10,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  listaIcones: {
    width: '100%',
    height: 140,
    flexGrow: 0,
  },
  icone: {
    width: 50,
    height: 50,
    margin: 8,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  iconeSelecionado: {
    borderColor: '#038C8C',
  },
  listaItens: {
    width: '100%',
    height: 160,
    flexGrow: 0,
    marginTop: 8,
  },
  listaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    borderLeftWidth: 4,
    borderLeftColor: '#038C8C',
  },
  listaIcone: {
    width: 24,
    height: 24,
    marginRight: 10,
  },
  botaoFixo: {
    backgroundColor: '#038C8C',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: 'center',
    width: '80%',
    marginTop: 16,
  },
});
