import { StyleSheet } from 'react-native';

const stylesNovoAmbiente = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#40E0D0',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    marginBottom: 20,
  },
  input: {
    width: '80%',
    height: 50,
    backgroundColor: '#fff',
    borderRadius: 8,
    paddingHorizontal: 10,
    fontSize: 18,
    elevation: 2,
    marginBottom: 20,
  },
  button: {
    backgroundColor: '#007bff',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center',
    elevation: 3,
    marginTop: 20,
    width: '80%',
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
  },
  containerCriacao: {
    width: '90%',
    backgroundColor: '#ffffffee',
    borderRadius: 10,
    padding: 20,
    marginTop: 20,
    alignItems: 'center',
    elevation: 3,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginBottom: 15,
  },
  itemInput: {
    flex: 1,
    height: 50,
    backgroundColor: '#fff',
    borderRadius: 8,
    paddingHorizontal: 10,
    fontSize: 18,
    elevation: 2,
  },
  addButton: {
    height: 50,
    width: 50,
    backgroundColor: '#007bff',
    marginLeft: 10,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
  },
  iconesContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    flexWrap: 'wrap',
    width: '100%',
    marginBottom: 20,
  },
  icone: {
    width: 50,
    height: 50,
    margin: 8,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  iconeSelecionado: {
    borderColor: '#007bff',
  },
  listaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 10,
    marginBottom: 10,
    width: '100%',
    elevation: 1,
  },
  listaIcone: {
    width: 24,
    height: 24,
    marginRight: 10,
  },
});

export default stylesNovoAmbiente;
